version: "3"
services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

