# Stage 1: Builder
FROM node:18 AS builder
WORKDIR /app
COPY app/package*.json ./
RUN npm install
COPY app/app.js .

# Stage 2: Runtime
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3000
CMD ["node", "app.js"]

