name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        description: "Docker Hub image name"
        required: true
        type: string

      tag:
        description: "Short commit SHA"
        required: true
        type: string

    secrets:
      docker_username:
        description: "Docker Hub username"
        required: true

      docker_token:
        description: "Docker Hub access token"
        required: true

    outputs:
      image_url:
        description: "Full Docker image path"
        value: ${{ jobs.docker-build-push.outputs.image_url }}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    outputs:
      image_url: ${{ steps.image.outputs.image_url }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./2026/day-48/github-actions-capstone
          file: ./2026/day-48/github-actions-capstone/Dockerfile
          push: true
          tags: |
            ${{ secrets.docker_username }}/${{ inputs.image_name }}:latest
            ${{ secrets.docker_username }}/${{ inputs.image_name }}:sha-${{ inputs.tag }}


      - name: Set Image URL
        id: image
        run: |
          IMAGE_URL="${{ secrets.docker_username }}/${{ inputs.image_name }}:sha-${{ inputs.tag }}"
          echo "image_url=$IMAGE_URL" >> "$GITHUB_OUTPUT"
          echo "Docker image: $IMAGE_URL"

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ secrets.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}
          format: table
          output: trivy-report.txt
          severity: CRITICAL
          exit-code: 1
          trivyignores: ${{ github.workspace }}/.trivyignore

      - name: Upload Trivy scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.txt
